### ISSUE TITLE
Basic questions about droplets and IP addresses

### ISSUE THREAD

**Issue by Nick-Hope** [tbhaxor/ProxyForge#1]
This looks very interesting for me, as the IP of my single DigitalOcean droplet keeps getting blacklisted by a server that my website users need to authenticate themselves on (via a PHP cURL script on my site). Thankfully it keeps getting un-blacklisted some hours later.

Some basic questions:

1. Could I set this up remotely on a DigitalOcean droplet that serves my website, instead of on my local machine?

2. Is it required to set up some DigitalOcean droplets in advance of setting this up? Or just have an account, as the prerequisites say?

3. Would I still need to have 1 DigitalOcean droplet (currently $4/month minimum) per IP address? Or can this find/generate IP addresses some other way?

4. Would it be possible to configure ProxyForge so that an IP is prevented from being used in excess of X times per Y minutes? For example, to deal with a server that blacklists after more than 10 requests in a 5 minute period. Or is the IP rotation random?

**Comment by tbhaxor** [comment]
Hi @Nick-Hope! Thanks for showing interest in ProxyForge. I will try to answer your questions

1. Could I set this up remotely on a DigitalOcean droplet that serves my website, instead of on my local machine?

Yes, the ProxyForge infrastructure is only intended to be hosted on DigitalOcean servers. You cannot set this up on your local system. However, once the script has executed and all of the resources have been provisioned, you can use the IP address on your local system for testing or anywhere else. [Check this video](https://asciinema.org/a/610686)

2. Is it required to set up some DigitalOcean droplets in advance of setting this up? Or just have an account, as the prerequisites say?

You only need to have your DigitalOcean account with updated billing information.

> [!TIP]
> For your testing, I would recommend you to signup from my referral link. You will get $200 for 60 days as credit.

3. Would I still need to have 1 DigitalOcean droplet (currently $4/month minimum) per IP address? Or can this find/generate IP addresses some other way?

Number of droplets depends on how many IPs you want to rotate. Let's suppose you want a pool of $10$ IPs, then you need to have $10$ droplets. Based on the size of droplet you have selected, let's consider $n$ USD, then you will be billed $10 * n + 12$ USD. Additional 12 USD will be billed for Load Balancer. 

4. Would it be possible to configure ProxyForge so that an IP is prevented from being used in excess of X times per Y minutes? For example, to deal with a server that blacklists after more than 10 requests in a 5 minute period. Or is the IP rotation random?

The latter one. IP rotation is randomised. More specifically, the load balancer automatically selected the droplet to pass through the request based on [Least Connection](https://www.digitalocean.com/resources/article/load-balancing#load-balancing-for-scalability) algorithm.

**Comment by Nick-Hope** [comment]
@tbhaxor Thank you for your quick and thorough response. Very helpful.

**Comment by tbhaxor** [comment]
I am closing this issue for now. Feel free to re-open it in case you have any query.
